### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by 0Void2391** [PanagiotisIatrou/chess-auto-bot#1]
there are 2 bugs i found while using this project. The first one is the bot not clicking the right spots. The 2nd is the bot after some time stops to update

**Comment by PanagiotisIatrou** [comment]
Hello. Thanks for the feedback! Could you provide some more information such as the operating system you are using? Are you using a virtual machine by any chance? Also, is the browser on fullscreen or windowed mode? Are you noticing an offset on the clicking spots or are they completely off?

**Comment by 0Void2391** [comment]
I'm using windows 10, i tried with both full screen and windowed mode. I noticed that the bot was clicking higher than where it should have clicked. If you want to dm me my discord is 0_Void#4435

**Comment by PanagiotisIatrou** [comment]
After some talking with @0Void2391 the issue regarding the clicking spots seemed not to be related to the repository itself, but with the Windows scale and layout value not being set to 100%. I have created a separate issue for this: #2 

As for the second issue, there was indeed a bug specifically affecting the chess.com bot that was making the search of the list of moves inconsistent.  I fixed it in c64d8a2b8713af176c8bc8ca88943b34df79472b
