### ISSUE TITLE
Can't find moves list

### ISSUE THREAD

**Issue by Whitesun123** [PanagiotisIatrou/chess-auto-bot#33]
Whenever I press 'Start' I only get an message box saying "Cant find moves list!" and no error output in the console.
I am using Python 3.11.

**Comment by PanagiotisIatrou** [comment]
Hello @Whitesun123. What operating system are you using? Also, are you sure you are in-game when pressing the Start button?

**Comment by Whitesun123** [comment]
I am on Windows 11, I have tried in-game and before game and get the same error.
