### ISSUE TITLE
Cannot use any other engines other than Stockfish 15.1

### ISSUE THREAD

**Issue by Baconartist** [PanagiotisIatrou/chess-auto-bot#35]
I wish to use the zappa bot. I put in the executable in the path, yet it will say "starting" indefinitely. I have loaded this same executable inside arena, and it works.

**Comment by PanagiotisIatrou** [comment]
Hello, currently there is no support for engines other than Stockfish. I am closing this issue as it is a duplicate of https://github.com/PanagiotisIatrou/chess-auto-bot/issues/21
