### ISSUE TITLE
Suggestion to add a new feature) And also thank you for a great bot.

### ISSUE THREAD

**Issue by Drogss** [PanagiotisIatrou/chess-auto-bot#4]
Will there be an addition of a function so that when the key is pressed the bot walks. For example, I press "5" and he makes a move.

**Comment by PanagiotisIatrou** [comment]
Hello @Drogss. Yes, that is a nice idea! I will notify you when this becomes available.

**Comment by Drogss** [comment]
Thank you very much I will look forward to it

**Comment by PanagiotisIatrou** [comment]
Hello @Drogss. This feature is finally implemented (5047212aa33162c01c7dedaf8431d8fec2dafb1f) in the form of a manual mode. When enabled, you can press 3 to make a move. I also added a shortcut to start the bot by pressing 1 and stop it by pressing 2. Note that if you make any settings while the bot is running you need to stop and start it again to apply the changes.

You can try it yourself by downloading the latest version.

**Comment by Drogss** [comment]
Great, I'll try it out now

**Comment by Drogss** [comment]
@PanagiotisIatrou The "venv" folder has disappeared, and because of this, the bot does not start
![image](https://user-images.githubusercontent.com/120088795/208145088-dab81201-42d7-468d-956f-4fc67fec1d86.png)

**Comment by PanagiotisIatrou** [comment]
The venv folder is not a part of the repository. Instead it is created by the user. You can follow the steps in the installation to create it again.

**Comment by Drogss** [comment]
Everything works fine thank you very much
