### ISSUE TITLE
Can't find board.

### ISSUE THREAD

**Issue by LFL38** [PanagiotisIatrou/chess-auto-bot#46]
I've used this tool in the past, mid 2022 I think. I've had the exact same problem in the past but I can't remember how I fixed it, I open the browser after connecting stockfish to it, I press start and it just says "Can't find board" after a couple of seconds.

Thanks in advance.

**Comment by PanagiotisIatrou** [comment]
Hello @LFL38 

Thank you for your feedback. It was indeed a bug that was just fixed by @MarcusM2092 in 93a4efea6a9d3a7875cfadf5de7048e6180cd630.

You can download the latest version and it should work.
