### ISSUE TITLE
Cant detect that chrome is installed

### ISSUE THREAD

**Issue by marzzyyyy** [PanagiotisIatrou/chess-auto-bot#48]
![obraz_2023-08-23_212920703](https://github.com/PanagiotisIatrou/chess-auto-bot/assets/140838363/ddfd4e17-64ec-4b6a-bfd4-2b669aa8a14f)

Think it mightve happened since chrome got 116 update as i already implemented the change to gui.py to get the 114 chromium driver and it worked fine till today but no matter what i do (reinstall chrome, install 114 chrome ver, make sure to check if 114 chromium driver works) it always just pops up this error.

Any kind soul with better understanding of python knows a workaround to make it work again and open chrome like it used to?

**Comment by shadow-magic** [comment]
pip install --upgrade webdriver_manager
