### ISSUE TITLE
Can't find moves list + fix

### ISSUE THREAD

**Issue by shadow-magic** [PanagiotisIatrou/chess-auto-bot#51]
Chess.com changed so now you get can't find moves list
Fix:
line 71| move_list_elem = self.chrome.find_element(By.TAG_NAME, "vertical-move-list")
change to
line 71 move_list_elem = self.chrome.find_element(By.TAG_NAME, "wc-vertical-move-list")

**Comment by Smellon69** [comment]
how did you even get it to work in general because mine won't even open. do I need to use a older chrome version and if so how

**Comment by Smellon69** [comment]
ok I fixed all that and used slimjet to download 2022 chrome but it can't find the board for some reason

**Comment by AnonGhostID** [comment]
It works! Thanks. Can you explain how did you find that? Or how you debug that? So one day if those element changed again i can fix it by myself 😃

**Comment by PanagiotisIatrou** [comment]
Hello @shadow-magic 

Thank you for your feedback. It was indeed a bug that was just fixed by @MarcusM2092 in 93a4efea6a9d3a7875cfadf5de7048e6180cd630.

You can download the latest version and it should work.
