### ISSUE TITLE
no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_119.0.6045

### ISSUE THREAD

**Issue by GuardianAngelWw** [PanagiotisIatrou/chess-auto-bot#53]
\chess-auto-bot\venv\Lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_119.0.6045

**Comment by AnonGhostID** [comment]
you need to update your webdriver_manager by updating it via pip.

`pip install --upgrade webdriver_manager`

**Comment by greenteabots** [comment]
does not work! still getting that error after updating

**Comment by LFL38** [comment]
> does not work! still getting that error after updating

Greetings, I seem to have found a fix!
Please download and install an older version of chrome such as 90.0.4430.72 from [here](https://www.slimjet.com/chrome/google-chrome-old-version.php), and it should work!

**Comment by PanagiotisIatrou** [comment]
Hello @GuardianAngelWw,

Thanks for pointing out, I fixed it in the latest commit https://github.com/PanagiotisIatrou/chess-auto-bot/commit/9b70ec15a9912799430897a89f5a1acf47bc62fe
You can do a clean installation and it will work.
