### ISSUE TITLE
Feature Suggestion: Depth Limit and Overlay Mode

### ISSUE THREAD

**Issue by Corus86** [PanagiotisIatrou/chess-auto-bot#8]
Rather than use get_best_move(), I think you can use _put("go depth x") where x is the value of the depth set by the user. This would allow limitation in strength of the engine used. Also, it would probably be a little more work, but an overlay mode, where best move is displayed but not played, would be pretty nice.

**Comment by Corus86** [comment]
There's also set_depth(self, depth_value: int = x) within the api for limiting depth, which might be the better way to implement this depth limit.

**Comment by PanagiotisIatrou** [comment]
Hello @Corus86. Thanks for the ideas! The overlay would be indeed a good addition.  As for the depth, I'll look more into it and I will notify you if I manage to implement it.

**Comment by PanagiotisIatrou** [comment]
Hello @Corus86. I just pushed a screen overlay mode that shows an arrow with the best move (13e4baf4b1c07c55093c55b4abdd1a3be6821630).
**Note** that it only works in manual mode.
I plan to also push an update with smaller arrows indicating alternative less effective candidate moves in the future

Let me know if you try it!

**Comment by PanagiotisIatrou** [comment]
Hello, again @Corus86. depth selection was added to the bot via a slider in the GUI by @xHeaven (https://github.com/PanagiotisIatrou/chess-auto-bot/commit/fa035f0df199d9c5645cc98d23f4dee58ee943d4)
